/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.MienTrung;
import Controller.DAOHangXeMT;
import Model.HangXeMT;
import com.sun.jdi.connect.spi.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hvt02
 */
public class MT_HangXe extends javax.swing.JFrame {

     private List<HangXeMT> hxmientrung;
    private DefaultTableModel Model;
    private Connection conn;
    int SelecteđIndex;
    /** Creates new form HangXeMT */
    public MT_HangXe() {
         initComponents();
        this.setLocationRelativeTo(null);
        Model = (DefaultTableModel)tbHX.getModel();
        showTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHX = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHangXe = new javax.swing.JTextField();
        txtTenHang = new javax.swing.JTextField();
        btnAddHX = new javax.swing.JButton();
        btnEditHX = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        btnSearchHX = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbHX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "ID Hãng Xe", "Tên Hãng Xe"
            }
        ));
        tbHX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHXMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbHX);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Danh Sách Hãng Xe");

        jLabel2.setText("ID Hãng Xe");

        jLabel3.setText("Tên Hãng Xe");

        btnAddHX.setText("Thêm");
        btnAddHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHXActionPerformed(evt);
            }
        });

        btnEditHX.setText("Sửa");
        btnEditHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHXActionPerformed(evt);
            }
        });

        btnout.setText("Quay lại");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });

        btnSearchHX.setText("Tìm kiếm");
        btnSearchHX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHXActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenHang, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtHangXe)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchHX, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddHX, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(btnEditHX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddHX))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditHX))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnout)
                    .addComponent(btnSearchHX)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHXActionPerformed
        HangXeMT mt =new HangXeMT();
        mt.setID_hangxe(txtHangXe.getText());
        mt.setTenHangXe(txtTenHang.getText());
    
        // txtTenHang.getText().equals("")
        if( txtHangXe.getText().equals("") || txtTenHang.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Thông tin không được để trống");
        }else {
            new DAOHangXeMT().AddCar(mt);
            showTable();
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        }
    }//GEN-LAST:event_btnAddHXActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         SelecteđIndex = tbHX.getSelectedRow();
        HangXeMT mt = hxmientrung.get(SelecteđIndex);
        JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xóa" +mt.getTenHangXe()+ "ra khỏi danh sách?");
        new DAOHangXeMT().DeleteCar(mt.getID_hangxe());
        showTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHXActionPerformed
        SelecteđIndex = tbHX.getSelectedRow();
        HangXeMT m = hxmientrung.get(SelecteđIndex);
        new DAOHangXeMT().DeleteCar(m.getID_hangxe());
        if(hxmientrung.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để sửa");
        }else if(SelecteđIndex == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn dữ liệu để sửa");
        }else{
            HangXeMT mt =new HangXeMT();
            mt.setID_hangxe(txtHangXe.getText());
            mt.setTenHangXe(txtTenHang.getText());
            if( txtHangXe.getText().equals("") || txtTenHang.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Thông tin không được để trống");
            }else {
                new DAOHangXeMT().AddCar(mt);
                showTable();
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            }
        }
    }//GEN-LAST:event_btnEditHXActionPerformed

    private void btnSearchHXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHXActionPerformed
        String Name = txtHangXe.getText().toString();        
            if(Name.length() > 0){
                hxmientrung = new DAOHangXeMT().findbyName(Name);
                 Model.setRowCount(0);
                for(HangXeMT mt:hxmientrung){
                    Model.addRow(new Object[]{
                    tbHX.getRowCount()+1,mt.getID_hangxe(),mt.getTenHangXe()
                });
            }
        }
    }//GEN-LAST:event_btnSearchHXActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        MT_ManagerCar l = new MT_ManagerCar();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnoutActionPerformed

    private void tbHXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHXMouseClicked
        SelecteđIndex = tbHX.getSelectedRow();
        HangXeMT mt = hxmientrung.get(SelecteđIndex);
        txtHangXe.setText(mt.getID_hangxe());
        txtTenHang.setText(mt.getTenHangXe());
    }//GEN-LAST:event_tbHXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MT_HangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MT_HangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MT_HangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MT_HangXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MT_HangXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHX;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditHX;
    private javax.swing.JButton btnSearchHX;
    private javax.swing.JButton btnout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbHX;
    private javax.swing.JTextField txtHangXe;
    private javax.swing.JTextField txtTenHang;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
        hxmientrung = (List<HangXeMT>) new DAOHangXeMT().getListHangXeMT();
        Model.setRowCount(0);
        for(HangXeMT mt:hxmientrung){
            Model.addRow(new Object[]{
            tbHX.getRowCount()+1,mt.getID_hangxe(),mt.getTenHangXe()
            });
        }
    }

}
