/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.MienBac;


import View.MienBac.*;
import Controller.DAOLichDiChuyenMB;
import Model.LichDiChuyenMB;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/***/
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
/**
 *
 * @author Hvt02
 */
public class MB_ManagerCalendar extends javax.swing.JFrame {

    /**
     * Creates new form MB_ManagerCalendar
     */
   private List<LichDiChuyenMB> calendarmt;
    private DefaultTableModel Model;
    int SelecteđIndex;
    public MB_ManagerCalendar() {
        initComponents();
        this.setLocationRelativeTo(null);
        Model = (DefaultTableModel)tbCalendarMB.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayDC = new javax.swing.JTextField();
        txtBenDenDc = new javax.swing.JTextField();
        cbTrangThaiDC = new javax.swing.JComboBox<>();
        txtTenHangDC = new javax.swing.JTextField();
        txtBienSoDC = new javax.swing.JTextField();
        txtBenKHDC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCalendarMB = new javax.swing.JTable();
        btnThemDC = new javax.swing.JButton();
        btnUpdateDC = new javax.swing.JButton();
        btnDeleteDC = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnFindDc = new javax.swing.JButton();
        btnRefestDC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LỊCH DI CHUYỂN CỦA XE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 11, 219, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Hãng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Biển số");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 45, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Trạng thái");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 61, 66, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Bến khởi hành");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 92, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Bến đến");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 61, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ngày dự kiến");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 79, 26));

        txtNgayDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDCActionPerformed(evt);
            }
        });
        getContentPane().add(txtNgayDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 40));
        getContentPane().add(txtBenDenDc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, 40));

        cbTrangThaiDC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang Chạy", "Còn Tại Bến", "Đã Hoàn Thành" }));
        getContentPane().add(cbTrangThaiDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 54, 137, 34));
        getContentPane().add(txtTenHangDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 180, 40));
        getContentPane().add(txtBienSoDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 180, 40));
        getContentPane().add(txtBenKHDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 40));

        tbCalendarMB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Hãng", "Biển Số", "Trạng Thái", "Bến Khởii Hành", "Bến Đến", "Ngày Dự Kiến"
            }
        ));
        tbCalendarMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCalendarMBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCalendarMB);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 840, 260));

        btnThemDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Create.png"))); // NOI18N
        btnThemDC.setText("Thêm");
        btnThemDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, -1));

        btnUpdateDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Edit.png"))); // NOI18N
        btnUpdateDC.setText("Sửa");
        btnUpdateDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 100, -1));

        btnDeleteDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Delete.png"))); // NOI18N
        btnDeleteDC.setText("Xóa");
        btnDeleteDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 90, -1));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Closed door.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        btnFindDc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Search.png"))); // NOI18N
        btnFindDc.setText("Tim Kiếm");
        btnFindDc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDcActionPerformed(evt);
            }
        });
        getContentPane().add(btnFindDc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        btnRefestDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Hinh/Refresh.png"))); // NOI18N
        btnRefestDC.setText("Refest");
        btnRefestDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefestDCActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefestDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 100, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/List.png"))); // NOI18N
        jButton1.setText("Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    private void btnThemDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDCActionPerformed
        LichDiChuyenMB mt =new LichDiChuyenMB();
        mt.setTenHangdc(txtTenHangDC.getText());
        mt.setBienSodc(txtBienSoDC.getText());
        mt.setTrangThai(cbTrangThaiDC.getSelectedItem().toString());
        mt.setDiTudc(txtBenKHDC.getText());
        mt.setDenBendc(txtBenDenDc.getText());
        mt.setNgayVaodc(txtNgayDC.getText());
        if(txtTenHangDC.getText().equals("") || txtBienSoDC.getText().equals("") || txtBenKHDC.getText().equals("")|| txtBenDenDc.getText().equals("")|| txtNgayDC.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Thông tin không được để trống");
        }else {
            new DAOLichDiChuyenMB().AddCarCalendar(mt);
            showTable();
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        }
 
    }//GEN-LAST:event_btnThemDCActionPerformed

    private void btnDeleteDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDCActionPerformed
       SelecteđIndex = tbCalendarMB.getSelectedRow();
        LichDiChuyenMB mt = calendarmt.get(SelecteđIndex);
        JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn xóa" +mt.getTenHangdc()+ "ra khỏi danh sách?");
        new DAOLichDiChuyenMB().DeleteCarCalender(mt.getIddc());
        showTable();
    }//GEN-LAST:event_btnDeleteDCActionPerformed

    private void btnUpdateDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDCActionPerformed
         SelecteđIndex = tbCalendarMB.getSelectedRow();
        LichDiChuyenMB m = calendarmt.get(SelecteđIndex);
        new DAOLichDiChuyenMB().DeleteCarCalender(m.getIddc());
        if(calendarmt.isEmpty()){
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để sửa");
        }else if(SelecteđIndex == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn dữ liệu để sửa");
        }else{
            LichDiChuyenMB mt =new LichDiChuyenMB();
            mt.setTenHangdc(txtTenHangDC.getText());
            mt.setBienSodc(txtBienSoDC.getText());
            mt.setTrangThai(cbTrangThaiDC.getSelectedItem().toString());
            mt.setDiTudc(txtBenKHDC.getText());
            mt.setDenBendc(txtBenDenDc.getText());
            mt.setNgayVaodc(txtNgayDC.getText());
            if(txtTenHangDC.getText().equals("") || txtBienSoDC.getText().equals("") || txtBenKHDC.getText().equals("")|| txtBenDenDc.getText().equals("")|| txtNgayDC.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Thông tin không được để trống");
            }else {
                new DAOLichDiChuyenMB().AddCarCalendar(mt);
                showTable();
                JOptionPane.showMessageDialog(this, "Sửa Thành Công");
            }
        }
    }//GEN-LAST:event_btnUpdateDCActionPerformed

    private void tbCalendarMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCalendarMBMouseClicked
        SelecteđIndex = tbCalendarMB.getSelectedRow();
        LichDiChuyenMB mt = calendarmt.get(SelecteđIndex);
        txtTenHangDC.setText(mt.getTenHangdc());
        txtBienSoDC.setText(mt.getBienSodc());
        cbTrangThaiDC.setSelectedItem(mt.getTrangThai());
        txtBenKHDC.setText(mt.getDiTudc());
        txtBenDenDc.setText(mt.getDenBendc());
        txtNgayDC.setText(mt.getNgayVaodc());
    }//GEN-LAST:event_tbCalendarMBMouseClicked

    private void btnFindDcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDcActionPerformed
       String Name = txtTenHangDC.getText();        
            if(Name.length() > 0){
                calendarmt = new DAOLichDiChuyenMB().findbyName(Name);
                 Model.setRowCount(0);
                for(LichDiChuyenMB mt:calendarmt){
                    Model.addRow(new Object[]{
                    tbCalendarMB.getRowCount()+1,mt.getTenHangdc(),mt.getBienSodc(),mt.getTrangThai(),mt.getDiTudc(),mt.getDenBendc(),mt.getNgayVaodc()
                });
            }
        }
    }//GEN-LAST:event_btnFindDcActionPerformed

    private void btnRefestDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefestDCActionPerformed
        txtTenHangDC.setText("");
        txtBienSoDC.setText("");
        txtBenKHDC.setText("");
        txtBenDenDc.setText("");
        txtNgayDC.setText("");
        showTable();
    }//GEN-LAST:event_btnRefestDCActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        MB_ManagerCar l = new MB_ManagerCar();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           JFileChooser jFileChooser = new JFileChooser();
           jFileChooser.showSaveDialog(this);
           File saveFile = jFileChooser.getSelectedFile();
           
           if(saveFile != null){
               saveFile = new File(saveFile.toString()+".xlsx");
               Workbook wb = new XSSFWorkbook();
               Sheet sheet = wb.createSheet("lichdukien");
               
               Row rowCol = sheet.createRow(0);
               for(int i=0;i<tbCalendarMB.getColumnCount();i++){
                   Cell cell = rowCol.createCell(i);
                   cell.setCellValue(tbCalendarMB.getColumnName(i));
               }
               
               for(int j=0;j<tbCalendarMB.getRowCount();j++){
                   Row row = sheet.createRow(j+1);
                   for(int k=0;k<tbCalendarMB.getColumnCount();k++){
                       Cell cell = row.createCell(k);
                       if(tbCalendarMB.getValueAt(j, k)!=null){
                           cell.setCellValue(tbCalendarMB.getValueAt(j, k).toString());
                       }
                   }
               }
               FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
               wb.write(out);
               wb.close();
               out.close();
               openFile(saveFile.toString());
           }else{
               JOptionPane.showMessageDialog(null,"Error al generar archivo");
           }
       }catch(FileNotFoundException e){
           System.out.println(e);
       }catch(IOException io){
           System.out.println(io);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNgayDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MB_ManagerCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MB_ManagerCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MB_ManagerCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MB_ManagerCalendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MB_ManagerCalendar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteDC;
    private javax.swing.JButton btnFindDc;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnRefestDC;
    private javax.swing.JButton btnThemDC;
    private javax.swing.JButton btnUpdateDC;
    private javax.swing.JComboBox<String> cbTrangThaiDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCalendarMB;
    private javax.swing.JTextField txtBenDenDc;
    private javax.swing.JTextField txtBenKHDC;
    private javax.swing.JTextField txtBienSoDC;
    private javax.swing.JTextField txtNgayDC;
    private javax.swing.JTextField txtTenHangDC;
    // End of variables declaration//GEN-END:variables

    private void showTable() {
         calendarmt = (List<LichDiChuyenMB>) new DAOLichDiChuyenMB().getListMT();
        Model.setRowCount(0);
        for(LichDiChuyenMB mt:calendarmt){
            Model.addRow(new Object[]{
            tbCalendarMB.getRowCount()+1,mt.getTenHangdc(),mt.getBienSodc(),mt.getTrangThai(),mt.getDiTudc(),mt.getDenBendc(),mt.getNgayVaodc()
            });
        }
    }
}
