/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Main;

import View.MienNam.MN_ManagerCar;
import View.MienBac.MB_ManagerCar;
import View.MienTrung.MT_ManagerCar;

/**
 *
 * @author Hvt02
 */
public class main_screen extends javax.swing.JFrame {

    /**
     * Creates new form MainCar
     */
    public main_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMBac = new javax.swing.JButton();
        btnMTrung = new javax.swing.JButton();
        btnMNam = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMBac.setBackground(new java.awt.Color(51, 204, 255));
        btnMBac.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnMBac.setText("Trạm xe Miền Bắc");
        btnMBac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMBacActionPerformed(evt);
            }
        });
        getContentPane().add(btnMBac, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 180, 66));

        btnMTrung.setBackground(new java.awt.Color(102, 204, 255));
        btnMTrung.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnMTrung.setText("Trạm xe Miền Trung");
        btnMTrung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMTrungActionPerformed(evt);
            }
        });
        getContentPane().add(btnMTrung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 200, 68));

        btnMNam.setBackground(new java.awt.Color(51, 204, 255));
        btnMNam.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnMNam.setText("Trạm xe Miền Nam");
        btnMNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMNamActionPerformed(evt);
            }
        });
        getContentPane().add(btnMNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 210, 68));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Hinh/Exit.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anh-nen-1-min.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMBacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBacActionPerformed
        MB_ManagerCar l = new MB_ManagerCar();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMBacActionPerformed

    private void btnMTrungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMTrungActionPerformed
        MT_ManagerCar l = new MT_ManagerCar();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMTrungActionPerformed

    private void btnMNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMNamActionPerformed
        MN_ManagerCar l = new MN_ManagerCar();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMNamActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        login_account l = new login_account();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMBac;
    private javax.swing.JButton btnMNam;
    private javax.swing.JButton btnMTrung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
